name: Dependency Check

on:

  push:

    branches: [ "master" ]   # use "main" if that's your default

  pull_request:

    branches: [ "master" ]

jobs:

  dependency-check:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository

        uses: actions/checkout@v4

      - name: Set up JDK 17

        uses: actions/setup-java@v4

        with:

          distribution: 'temurin'

          java-version: '17'

          cache: 'maven'

      - name: Build with Maven

        run: mvn -B clean install -DskipTests

      - name: Cache OWASP Dependency-Check DB

        uses: actions/cache@v4

        with:

          path: ~/.m2/repository/org/owasp/dependency-check-data

          key: ${{ runner.os }}-dcdb-${{ hashFiles('**/pom.xml') }}

          restore-keys: |

            ${{ runner.os }}-dcdb-

      - name: OWASP Dependency-Check (report)

        run: mvn -B org.owasp:dependency-check-maven:9.1.0:aggregate

      # - name: OWASP Dependency-Check (enforce)

      #   run: mvn -B org.owasp:dependency-check-maven:9.1.0:check -DfailOnCVSS=7.0

      - name: Upload report

        uses: actions/upload-artifact@v4

        with:

          name: dependency-check-report

          path: |

            target/dependency-check-report.html

            target/dependency-check-report.xml

            target/dependency-check-report.json

            target/dependency-check-report.csv

